import * as React from 'react';
import Head from 'next/head';
import { AppProps } from 'next/app';
import { AppCacheProvider } from '@mui/material-nextjs/v14-pagesRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../theme';
import NavBar from '../components/NavBar';

export default function MyApp(props: AppProps) {
  const { Component, pageProps } = props;
  return (
    <AppCacheProvider {...props}>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        <NavBar />
        <Component {...pageProps} />
      </ThemeProvider>
    </AppCacheProvider>
  );
}

// import "../styles/globals.css";
// import type { AppProps } from "next/app";
// // import theme from "../theme";
// import { ThemeProvider } from '@mui/material/styles';
// import CssBaseline from '@mui/material/CssBaseline';
// import NavBar from "../components/NavBar";
// import { AppCacheProvider } from '@mui/material-nextjs/v14-pagesRouter';
//  // Or `v1X-pages` if you are using Next.js v1X
//  import Head from "next/head";

// // export default function App({ Component, pageProps }: AppProps) {
// //   return (
// //     <ThemeProvider theme={theme}>
// //       <CssBaseline />
// //       <NavBar />
// //       <Component {...pageProps} />
// //     </ThemeProvider>
// //   )
// // };

// import { 
//   // ThemeProvider, 
//   createTheme } from '@mui/material/styles';
// import { Roboto } from 'next/font/google';

// const roboto = Roboto({
//   weight: ['300', '400', '500', '700'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-roboto',
// });

// const theme = createTheme({
//   typography: {
//     fontFamily: var(--font-roboto),
//   },
// });


//  export default function MyApp(props: AppProps) {
//   const { Component, pageProps } = props;
//    return (
//     <AppCacheProvider {...props}>
//       <Head>
//         <title>Staiin Studio</title>
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <ThemeProvider theme={theme}>
//         <main className={roboto.variable}>
//           <Component {...pageProps} />
//         </main>
//       </ThemeProvider>
//     </AppCacheProvider>
//    );
//  }
